### ISSUE TITLE
Error with selecting course setting

### ISSUE THREAD

**Issue by paulyting** [strangerstudios/pmpro-courses#28]
In the settings where you must choose a module, it's possible to select between Default, LearnDash, or LifterLMS.

I chose the default setting, clicked Save Settings, and it said successful.

However the checkbox then unticks itself and there is no course menu item in the admin menu.

I have installed this on a clean server without issues so there seems to be a plugin conflict I can't find.

**Environment**
Wordpress 5.8.1
PHP 8.0
Paid Memberships Pro 2.6.3

**Comment by thereferralclub** [comment]
I am having exactly the same issue.

Was the casue of this ever found?

**Comment by sc0ttkclark** [comment]
I'll take a look at this today, thanks for checking in @thereferralclub

**Comment by sc0ttkclark** [comment]
I have a fix for this that I'm working on a release for now.
