### ISSUE TITLE
Updating to PMPro courses 1.2.2 breaks existing links

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/pmpro-courses#52]
**Describe the bug**
Updating PMPro Courses to 1.2.2 causes existing lesson URLs to change. The `lesson` post type slug is rewritten to `pmpro_lesson` . 

This can be problematic if you have previously shared lesson links or hardcoded them somewhere.

**To Reproduce**
1. Install an older version of PMPro Courses eg. 1.2.1 
2. Create a course and add a lesson.
3. Visit the course page and make note of the lesson URL.
4. Update to PMPro Courses 1.2.2
5. Visit the lesson URL from Step 3, observe 404

**Expected behavior**
Pre-existing lesson URLs still lead to the lesson page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
PMPro 2.11.2
PMPro Courses for Membership 1.2.2
WP 6.2.2
</details>

**Comment by andrewlimaza** [comment]
To add a note here for others that may come across this issue, I had replicated it at one point but then it cleared itself.

It's worth trying the following:

* Deactivate (but do not delete) and re-activate the `pmpro-courses` plugin to flush rewrite rules.
* Change modules (toggle between modules save and choose your previous module and save again).

**Comment by andrewlimaza** [comment]
Also deactivating the conflicting LMS plugin solves things, you should really only use one LMS plugin on a site that shares courses and lesson slugs.

**Comment by ideadude** [comment]
I think this bug here was the issue: https://github.com/strangerstudios/pmpro-courses/commit/e95bc5932bd34acdfa4c2b1bcafcc66fb29922d0

I will do some more testing and push out a point release ASAP.
